/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessForgotPasswordRouteImport } from './routes/access.forgot-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessForgotPasswordRoute = AccessForgotPasswordRouteImport.update({
  id: '/access/forgot-password',
  path: '/access/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access/forgot-password': typeof AccessForgotPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access/forgot-password': typeof AccessForgotPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access/forgot-password': typeof AccessForgotPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/access/forgot-password'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/access/forgot-password'
  id: '__root__' | '/' | '/access/forgot-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessForgotPasswordRoute: typeof AccessForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/forgot-password': {
      id: '/access/forgot-password'
      path: '/access/forgot-password'
      fullPath: '/access/forgot-password'
      preLoaderRoute: typeof AccessForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessForgotPasswordRoute: AccessForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
