/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessClockInRouteImport } from './routes/access.clock-in'
import { Route as AccessCreateAccountRouteImport } from './routes/access.create-account'
import { Route as AccessForgotPasswordRouteImport } from './routes/access.forgot-password'
import { Route as AccessManagerPinRouteImport } from './routes/access.manager-pin'
import { Route as AccessSelectStationRouteImport } from './routes/access.select-station'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessClockInRoute = AccessClockInRouteImport.update({
  id: '/access/clock-in',
  path: '/access/clock-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessCreateAccountRoute = AccessCreateAccountRouteImport.update({
  id: '/access/create-account',
  path: '/access/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessForgotPasswordRoute = AccessForgotPasswordRouteImport.update({
  id: '/access/forgot-password',
  path: '/access/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessManagerPinRoute = AccessManagerPinRouteImport.update({
  id: '/access/manager-pin',
  path: '/access/manager-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessSelectStationRoute = AccessSelectStationRouteImport.update({
  id: '/access/select-station',
  path: '/access/select-station',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access/clock-in': typeof AccessClockInRoute
  '/access/create-account': typeof AccessCreateAccountRoute
  '/access/forgot-password': typeof AccessForgotPasswordRoute
  '/access/manager-pin': typeof AccessManagerPinRoute
  '/access/select-station': typeof AccessSelectStationRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access/clock-in': typeof AccessClockInRoute
  '/access/create-account': typeof AccessCreateAccountRoute
  '/access/forgot-password': typeof AccessForgotPasswordRoute
  '/access/manager-pin': typeof AccessManagerPinRoute
  '/access/select-station': typeof AccessSelectStationRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access/clock-in': typeof AccessClockInRoute
  '/access/create-account': typeof AccessCreateAccountRoute
  '/access/forgot-password': typeof AccessForgotPasswordRoute
  '/access/manager-pin': typeof AccessManagerPinRoute
  '/access/select-station': typeof AccessSelectStationRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access/clock-in'
    | '/access/create-account'
    | '/access/forgot-password'
    | '/access/manager-pin'
    | '/access/select-station'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access/clock-in'
    | '/access/create-account'
    | '/access/forgot-password'
    | '/access/manager-pin'
    | '/access/select-station'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/access/clock-in'
    | '/access/create-account'
    | '/access/forgot-password'
    | '/access/manager-pin'
    | '/access/select-station'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessClockInRoute: typeof AccessClockInRoute
  AccessCreateAccountRoute: typeof AccessCreateAccountRoute
  AccessForgotPasswordRoute: typeof AccessForgotPasswordRoute
  AccessManagerPinRoute: typeof AccessManagerPinRoute
  AccessSelectStationRoute: typeof AccessSelectStationRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/clock-in': {
      id: '/access/clock-in'
      path: '/access/clock-in'
      fullPath: '/access/clock-in'
      preLoaderRoute: typeof AccessClockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/create-account': {
      id: '/access/create-account'
      path: '/access/create-account'
      fullPath: '/access/create-account'
      preLoaderRoute: typeof AccessCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/forgot-password': {
      id: '/access/forgot-password'
      path: '/access/forgot-password'
      fullPath: '/access/forgot-password'
      preLoaderRoute: typeof AccessForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/manager-pin': {
      id: '/access/manager-pin'
      path: '/access/manager-pin'
      fullPath: '/access/manager-pin'
      preLoaderRoute: typeof AccessManagerPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/select-station': {
      id: '/access/select-station'
      path: '/access/select-station'
      fullPath: '/access/select-station'
      preLoaderRoute: typeof AccessSelectStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessClockInRoute: AccessClockInRoute,
  AccessCreateAccountRoute: AccessCreateAccountRoute,
  AccessForgotPasswordRoute: AccessForgotPasswordRoute,
  AccessManagerPinRoute: AccessManagerPinRoute,
  AccessSelectStationRoute: AccessSelectStationRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
